apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immo-scraper
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: env-var-secret
  envs:
  - .env
resources:
- resources/namespace.yaml
- resources/deployment.yaml
commonLabels:
  app: immo-scraper
